### ISSUE TITLE
pkg subsystemctl is removed from aur?

### ISSUE THREAD

**Issue by HsingYun** [sorah/subsystemctl#2]
https://aur.archlinux.org/packages/subsystemctl 
return 404 for now

**Comment by sorah** [comment]
Yes, they don’t accept WSL exclusive packages now. I’ll publish PKGBUILD directly in this repo soon.

**Comment by HsingYun** [comment]
> Yes, they don’t accept WSL exclusive packages now. I’ll publish PKGBUILD directly in this repo soon.

thanks, I'm using https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=subsystemctl as a temporary substitute

**Comment by sorah** [comment]
noted (but forgot to close) https://github.com/sorah/subsystemctl#arch-linux
