### ISSUE TITLE
404 PAGE

### ISSUE THREAD

**Issue by elio200quick** [sorah/subsystemctl#3]
https://aur.archlinux.org/packages/subsystemctl
404 - Page Not Found
Sorry, the page you've requested does not exist.

**Comment by sorah** [comment]
dupe. #2, PKGBUILD link was updated at commit https://github.com/sorah/subsystemctl/commit/242cdb08e0614e1cc6280e09516c04c9c987dd45

AUR doesn't welcome WSL exclusive software. Blame TUs...
